CREATE DATABASE FamilyBudget
GO

USE FamilyBudget
GO

CREATE TABLE FAMILY
(
	FAMILY_ID INT NOT NULL PRIMARY KEY,
	FAMILY_NAME VARCHAR(50) NOT NULL
)

CREATE TABLE FAMILY_PERSON
(
	FAMILY_PERSON_ID INT NOT NULL PRIMARY KEY,
	FAMILY_PERSON_SURNAME VARCHAR(50) NOT NULL,
	FAMILY_PERSON_NAME VARCHAR(50) NOT NULL,
	FAMILY_PERSON_LASTNAME VARCHAR(50) NOT NULL,
	FAMILY_ROLE VARCHAR(25) NOT NULL UNIQUE,
	FAMILY_LOGIN VARCHAR(25) NOT NULL UNIQUE,
	FAMILY_PASSWORD VARCHAR(11) NOT NULL,
	FAMILY_ID INT NOT NULL FOREIGN KEY REFERENCES FAMILY(FAMILY_ID)
)

CREATE TABLE LINK_EXPENSES
(
	LINK_EXPENSES_ID INT NOT NULL PRIMARY KEY,
	FAMILY_PERSON_ID INT NOT NULL FOREIGN KEY REFERENCES FAMILY_PERSON(FAMILY_PERSON_ID),
	TOTAL_EXPENSES MONEY NOT NULL,
)

CREATE TABLE LINK_REVENUE
(
	LINK_REVENUE_ID INT NOT NULL PRIMARY KEY,
	FAMILY_PERSON_ID INT NOT NULL FOREIGN KEY REFERENCES FAMILY_PERSON(FAMILY_PERSON_ID),
	TOTAL_REVENUE MONEY NOT NULL,
)

CREATE TABLE EXPENSES -- –¿—’Œƒ€
(
	EXPENSES_ID INT NOT NULL PRIMARY KEY,
	EXPENSES_DESCRIPTION VARCHAR(50) NULL,
	LINK_EXPENSES_ID INT NOT NULL FOREIGN KEY REFERENCES LINK_EXPENSES(LINK_EXPENSES_ID),
	EXPENSES_MONEY MONEY NOT NULL,
)

CREATE TABLE REVENUE -- ƒŒ’Œƒ€
(
	REVENUE_ID INT NOT NULL PRIMARY KEY,
	REVENUE_DESCRIPTION VARCHAR(50) NULL,
	LINK_REVENUE_ID INT NOT NULL FOREIGN KEY REFERENCES LINK_REVENUE(LINK_REVENUE_ID),
	REVENUE_MONEY MONEY NOT NULL,
)

CREATE TABLE CATEGORY
(
	CATEGORY_ID INT NOT NULL PRIMARY KEY,
	CATEGORY_NAME VARCHAR(50) UNIQUE
)