USE FamilyBudget
GO

CREATE TRIGGER AUTO_MONEY
ON LINK_EXPENSES
AFTER INSERT 
AS 
BEGIN 
DECLARE @TOTAL_EXPENSES MONEY, @EXPENSES_ID INT 
SET @TOTAL_EXPENSES = (SELECT TOTAL_EXPENSES FROM LINK_EXPENSES) 
SET @EXPENSES_ID = (SELECT LINK_EXPENSES_ID FROM LINK_EXPENSES) 
UPDATE LINK_EXPENSES
SET TOTAL_EXPENSES = TOTAL_EXPENSES + @TOTAL_EXPENSES WHERE LINK_EXPENSES_ID = @EXPENSES_ID 
END